# -*- coding: utf-8 -*-
"""Personality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taPyeHGSiNG-UsT9hRLxK0DByIoRG4jg
"""

# ==============================================================================
# PROJET : PRÉDICTION DE PERSONNALITÉ (INTROVERTI/EXTRAVERTI)
# AUTEUR : JOHN BOREL TAGNE
# UE8    :  ML & DL
# DATE   : 01/08/2025
# ==============================================================================

# ==============================================================================
# --- ÉTAPE 0 : INSTALLATION ET IMPORTATION DES BIBLIOTHÈQUES ---
# ==============================================================================
print(">>> ÉTAPE 0 : Installation et Importation des bibliothèques...")

# Installation de Plotly pour les graphiques interactifs
!pip install -q plotly

# Imports classiques
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import joblib # Pour sauvegarder le modèle

# Imports pour le Prétraitement
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Imports pour les modèles de Machine Learning (ML)
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Imports pour les modèles de Deep Learning (DL)
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# Imports pour l'évaluation
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Imports pour les visualisations avancées
import plotly.express as px

print("Bibliothèques importées avec succès.\n")


# ==============================================================================
# --- ÉTAPE 1 : CHARGEMENT ET PREMIER APERÇU DES DONNÉES ---
# ==============================================================================
print("="*80)
print(">>> ÉTAPE 1 : Chargement et premier aperçu des données...")
print("="*80)

# Charger le jeu de données via KaggleHub
import kagglehub
path = kagglehub.dataset_download("rakeshkapilavai/extrovert-vs-introvert-behavior-data")
csv_file_path = os.path.join(path, "personality_dataset.csv")
df = pd.read_csv(csv_file_path)

print(f"Le jeu de données a été chargé depuis : {csv_file_path}\n")

# Afficher les informations de base
print("--- Informations générales (df.info()) ---")
df.info()

print("\n--- Aperçu des 5 premières lignes (df.head()) ---")
print(df.head())

print("\n--- Statistiques descriptives pour les colonnes numériques (df.describe()) ---")
print(df.describe())

print(f"\n--- Recherche de doublons ---")
print(f"Nombre de lignes dupliquées : {df.duplicated().sum()}")
print("\n")


# ==============================================================================
# --- ÉTAPE 2 : ANALYSE EXPLORATOIRE DES DONNÉES (EDA) APPROFONDIE ---
# ==============================================================================
print("="*80)
print(">>> ÉTAPE 2 : Analyse Exploratoire des Données (EDA) Approfondie...")
print("="*80)

# --- 2.1 Analyses Univariées (étude d'une seule variable à la fois) ---
print("\n--- 2.1 Analyses Univariées ---")

# 1. Distribution de la variable cible ('Personality')
plt.figure(figsize=(8, 6))
sns.countplot(x='Personality', data=df, palette='viridis')
plt.title('1. Distribution des types de personnalité (Cible)')
plt.ylabel('Count')
plt.xlabel('Personality')
plt.show()
print("Analyse 1 : Le jeu de données est parfaitement équilibré, ce qui est idéal pour l'entraînement.\n")

# 2. Distribution de la taille du cercle d'amis
plt.figure(figsize=(8, 6))
sns.histplot(df['Friends_circle_size'], kde=True, bins=20)
plt.title("2. Distribution de la taille du cercle d'amis")
plt.xlabel("Friends_circle_size")
plt.ylabel('Frequency')
plt.show()
print("Analyse 2 : La plupart des individus ont un cercle d'amis de taille moyenne (autour de 400-600).\n")

# 3. Distribution du temps passé seul
plt.figure(figsize=(8, 6))
sns.histplot(df['Time_spent_Alone'], kde=True, bins=20, color='orange')
plt.title("3. Distribution du temps passé seul")
plt.xlabel("Time_spent_Alone")
plt.ylabel('Frequency')
plt.show()
print("Analyse 3 : La distribution du temps passé seul est assez uniforme, sans pic majeur.\n")

# 4. Répartition de la peur de la scène
plt.figure(figsize=(8, 6))
sns.countplot(x='Stage_fear', data=df, palette='magma')
plt.title('4. Répartition des personnes ayant peur de la scène')
plt.ylabel('Count')
plt.xlabel('Stage_fear')
plt.show()
print("Analyse 4 : Une majorité de personnes dans ce dataset n'ont pas peur de la scène.\n")

# 5. Répartition de la fatigue sociale
plt.figure(figsize=(8, 6))
sns.countplot(x='Drained_after_socializing', data=df, palette='plasma')
plt.title('5. Répartition des personnes se sentant vidées après avoir socialisé')
plt.ylabel('Count')
plt.xlabel('Drained_after_socializing')
plt.show()
print("Analyse 5 : La majorité des personnes ne se sentent pas particulièrement vidées après des interactions sociales.\n")


# --- 2.2 Analyses Bivariées (étude de la relation entre deux variables) ---
print("\n--- 2.2 Analyses Bivariées ---")

# 1. Relation entre Peur de la scène et Personnalité
plt.figure(figsize=(8, 6))
sns.countplot(x='Stage_fear', hue='Personality', data=df, palette='viridis')
plt.title('1. Relation entre Peur de la scène et Personnalité')
plt.show()
print("Analyse 1 : Les personnes ayant peur de la scène sont quasi exclusivement introverties. C'est un indicateur très fort.\n")

# 2. Relation entre Taille du cercle d'amis et Personnalité (Graphique en violon)
plt.figure(figsize=(8, 6))
sns.violinplot(x='Personality', y='Friends_circle_size', data=df, palette='magma')
plt.title("2. Relation entre Taille du cercle d'amis et Personnalité")
plt.show()
print("Analyse 2 : Les extravertis ont non seulement un cercle d'amis plus grand en moyenne, mais la distribution est aussi plus large.\n")

# 3. Relation entre Temps passé seul et Taille du cercle d'amis (Nuage de points)
plt.figure(figsize=(10, 7))
sns.scatterplot(x='Time_spent_Alone', y='Friends_circle_size', hue='Personality', data=df, alpha=0.7)
plt.title("3. Relation entre Temps passé seul et Taille du cercle d'amis")
plt.xlabel("Time_spent_Alone")
plt.ylabel("Friends_circle_size")
plt.show()
print("Analyse 3 : On observe une corrélation négative. Plus une personne passe de temps seule, plus son cercle d'amis est petit. La couleur sépare bien les deux personnalités.\n")

# 4. Relation entre Fréquence de publication et Personnalité
plt.figure(figsize=(8, 6))
sns.boxplot(x='Personality', y='Post_frequency', data=df, palette='plasma')
plt.title("4. Relation entre Fréquence de publication sur les réseaux et Personnalité")
plt.show()
print("Analyse 4 : Les extravertis ont tendance à publier plus fréquemment sur les réseaux sociaux.\n")

# 5. Relation entre deux variables catégorielles : Peur de la scène et Fatigue sociale
ct = pd.crosstab(df['Stage_fear'], df['Drained_after_socializing'])
sns.heatmap(ct, annot=True, fmt='d', cmap='cividis')
plt.title('5. Heatmap entre Peur de la scène et Fatigue sociale')
plt.show()
print("Analyse 5 : Il y a un lien : la plupart des gens qui ont peur de la scène se sentent aussi vidés après avoir socialisé.\n")


# --- 2.3 Analyses Multivariées (étude de plus de deux variables) ---
print("\n--- 2.3 Analyses Multivariées ---")

# Création d'une copie pour l'encodage nécessaire aux visualisations multivariées
df_encoded_viz = df.copy()
# Encodage pour la visualisation
for col in ['Stage_fear', 'Drained_after_socializing', 'Personality']:
    df_encoded_viz[col] = pd.factorize(df[col])[0]
for col in ['Time_spent_Alone', 'Social_event_attendance', 'Going_outside', 'Friends_circle_size', 'Post_frequency']:
    df_encoded_viz[col] = pd.to_numeric(df_encoded_viz[col], errors='coerce')
    df_encoded_viz[col].fillna(df_encoded_viz[col].median(), inplace=True)


# 1. Matrice de Corrélation (Test de Corrélation)
plt.figure(figsize=(12, 10))
corr_matrix = df_encoded_viz.corr()
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm')
plt.title('1. Matrice de Corrélation de toutes les variables')
plt.show()
print("Analyse 1 : La variable cible 'Personality' est fortement corrélée avec 'Stage_fear' (0.83), 'Drained_after_socializing' (0.81) et 'Friends_circle_size' (0.76). C'est excellent pour la prédiction.\n")

# 2. Pair Plot pour visualiser les relations par paires
print("Analyse 2: Le Pair Plot montre les relations 2 à 2. On voit bien la séparation des classes (bleu/jaune) sur certaines paires de variables.")
sns.pairplot(df_encoded_viz[['Time_spent_Alone', 'Friends_circle_size', 'Post_frequency', 'Personality']], hue='Personality', palette='viridis')
plt.suptitle('2. Pair Plot de variables sélectionnées, coloré par Personnalité', y=1.02)
plt.show()

# 3. Nuage de points 3D interactif
print("Analyse 3 : Le graphique 3D interactif montre une séparation très nette des deux groupes dans l'espace. Les introvertis (0) sont groupés en bas à droite, les extravertis (1) en haut à gauche.")
fig = px.scatter_3d(df_encoded_viz,
                    x='Friends_circle_size',
                    y='Time_spent_Alone',
                    z='Post_frequency',
                    color='Personality',
                    title='3. Visualisation 3D interactive des clusters de personnalité')
fig.show()

# 4. Boxplot multivarié
print("\nAnalyse 4 : Les extravertis vont plus souvent à des événements sociaux, et ceux qui n'ont pas peur de la scène y vont encore plus.")
plt.figure(figsize=(10, 7))
sns.boxplot(x='Personality', y='Social_event_attendance', hue='Stage_fear', data=df)
plt.title('4. Présence aux événements sociaux par Personnalité et Peur de la scène')
plt.xticks([0, 1], ['Introverti', 'Extraverti']) # Les ticks peuvent rester en français car ils décrivent la catégorie
plt.show()

# 5. FacetGrid
print("\nAnalyse 5 : Ce graphique confirme la corrélation négative entre temps passé seul et taille du cercle d'amis, et montre que cette tendance est vraie que la personne se sente vidée socialement ou non.")
g = sns.FacetGrid(df, col="Drained_after_socializing", hue="Personality", height=5)
g.map(sns.scatterplot, "Time_spent_Alone", "Friends_circle_size", alpha=.7)
g.add_legend()
g.fig.suptitle('5. Relation Amis/Temps Seul, séparée par Fatigue Sociale', y=1.03)
plt.show()


# ==============================================================================
# --- ÉTAPE 3 : PRÉPARATION DES DONNÉES POUR LES MODÈLES ---
# ==============================================================================
print("="*80)
print(">>> ÉTAPE 3 : Préparation et nettoyage des données...")
print("="*80)

# 3.1. Nettoyage des valeurs numériques non-standard
print("Nettoyage des colonnes numériques...")
for col in ['Time_spent_Alone', 'Social_event_attendance', 'Going_outside', 'Friends_circle_size', 'Post_frequency']:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)
print("Nettoyage terminé.\n")

# 3.2. Encodage des variables catégorielles en nombres
print("Encodage des variables catégorielles (texte -> nombre)...")
df['Stage_fear'] = df['Stage_fear'].apply(lambda x: 1 if x == 'Yes' else 0)
df['Drained_after_socializing'] = df['Drained_after_socializing'].apply(lambda x: 1 if x == 'Yes' else 0)
df['Personality'] = df['Personality'].apply(lambda x: 1 if x == 'Extrovert' else 0)
print("Encodage terminé.\n")

# 3.3. Séparation des caractéristiques (X) et de la cible (y)
X = df.drop('Personality', axis=1)
y = df['Personality']

# 3.4. Séparation en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"Division des données : {len(X_train)} échantillons d'entraînement, {len(X_test)} échantillons de test.\n")

# 3.5. Mise à l'échelle des caractéristiques (Standardisation)
print("Mise à l'échelle (standardisation) des caractéristiques...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Mise à l'échelle terminée. Les données sont prêtes.\n")


# ==============================================================================
# --- ÉTAPE 4 : MODÉLISATION MACHINE LEARNING (4 MODÈLES) ---
# ==============================================================================
print("="*80)
print(">>> ÉTAPE 4 : Entraînement et Évaluation de 4 modèles de Machine Learning...")
print("="*80)

models_ml = {
    "Régression Logistique": LogisticRegression(random_state=42),
    "Arbre de Décision": DecisionTreeClassifier(random_state=42),
    "k-NN (k=5)": KNeighborsClassifier(n_neighbors=5),
    "SVM (SVC)": SVC(kernel='linear', random_state=42)
}

results_ml = {}

for name, model in models_ml.items():
    print(f"--- Entraînement du modèle : {name} ---")
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    results_ml[name] = accuracy
    print(f"Précision (Accuracy): {accuracy:.4f}")
    print("Rapport de classification :")
    print(classification_report(y_test, y_pred, target_names=['Introverti (0)', 'Extraverti (1)']))

    # Matrice de confusion
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Introverti', 'Extraverti'], yticklabels=['Introverti', 'Extraverti'])
    plt.title(f'Matrice de Confusion - {name}')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.show()

# ==============================================================================
# --- ÉTAPE 5 : MODÉLISATION DEEP LEARNING (3 MODÈLES) ---
# ==============================================================================
print("="*80)
print(">>> ÉTAPE 5 : Entraînement et Évaluation de 3 modèles de Deep Learning...")
print("="*80)

# Configuration commune
EPOCHS = 15
BATCH_SIZE = 32
INPUT_SHAPE = (X_train_scaled.shape[1],)

def create_dl_model(name="simple"):
    model = Sequential()
    model.add(Dense(16, activation='relu', input_shape=INPUT_SHAPE))

    if name == "deep":
        model.add(Dense(16, activation='relu')) # Couche supplémentaire

    if name == "dropout":
        model.add(Dropout(0.2)) # Couche de Dropout pour régularisation
        model.add(Dense(8, activation='relu'))

    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

models_dl = {
    "ANN Simple": create_dl_model("simple"),
    "ANN Profond": create_dl_model("deep"),
    "ANN avec Dropout": create_dl_model("dropout")
}

results_dl = {}

for name, model in models_dl.items():
    print(f"--- Entraînement du modèle : {name} ---")
    model.fit(X_train_scaled, y_train, epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=0)

    # Évaluation
    loss, accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)
    results_dl[name] = accuracy
    print(f"Précision (Accuracy): {accuracy:.4f}")

    y_pred_proba = model.predict(X_test_scaled)
    y_pred = (y_pred_proba > 0.5).astype(int).flatten()

    print("Rapport de classification :")
    print(classification_report(y_test, y_pred, target_names=['Introverti (0)', 'Extraverti (1)']))

    # Matrice de confusion
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', xticklabels=['Introverti', 'Extraverti'], yticklabels=['Introverti', 'Extraverti'])
    plt.title(f'Matrice de Confusion - {name}')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.show()


# ==============================================================================
# --- ÉTAPE 6 : SÉLECTION DU MEILLEUR MODÈLE ET SAUVEGARDE ---
# ==============================================================================
print("="*80)
print(">>> ÉTAPE 6 : Sélection et Sauvegarde du Meilleur Modèle...")
print("="*80)

# Combinaison de tous les résultats
all_results = {**results_ml, **results_dl}

# Trouver le meilleur modèle
best_model_name = max(all_results, key=all_results.get)
best_model_accuracy = all_results[best_model_name]

print(f"Le meilleur modèle est : '{best_model_name}' avec une précision de {best_model_accuracy:.2%}.\n")

# Sauvegarde du pipeline complet (modèle + scaler)
# On récupère l'instance du meilleur modèle (ML ou DL)
if best_model_name in models_ml:
    best_model_object = models_ml[best_model_name]
else:
    best_model_object = models_dl[best_model_name]

# On sauvegarde le modèle et le scaler dans un seul fichier
pipeline_to_save = {
    'model': best_model_object,
    'scaler': scaler
}

save_path = 'pipeline_personality.joblib'
joblib.dump(pipeline_to_save, save_path)

print(f"Le pipeline complet (modèle '{best_model_name}' et scaler) a été sauvegardé avec succès dans le fichier : '{save_path}'")
print("Ce fichier peut maintenant être chargé dans une autre application pour faire de nouvelles prédictions.")
print("\n")


# ==============================================================================
# --- ÉTAPE 7 : RAPPORT FINAL DÉTAILLÉ DU PROJET ---
# ==============================================================================
print("="*80)
print(">>> ÉTAPE 7 : RAPPORT FINAL DÉTAILLÉ DU PROJET")
print("="*80)

rapport_final = f"""
################################################################################
#                   RAPPORT FINAL : PROJET DE PRÉDICTION DE PERSONNALITÉ
################################################################################

**OBJECTIF DU PROJET :**
L'objectif était de construire un modèle de classification capable de prédire si un individu est introverti ou extraverti
en se basant sur des données comportementales. Le projet a été mené de l'analyse exploratoire jusqu'au déploiement
d'un modèle entraîné.

--------------------------------------------------------------------------------
**1. ANALYSE EXPLORATOIRE DES DONNÉES (EDA)**
--------------------------------------------------------------------------------
L'analyse initiale a révélé plusieurs informations cruciales :
- **Équilibre des données :** Le jeu de données est parfaitement équilibré avec 50% d'introvertis et 50% d'extravertis,
  ce qui élimine le besoin de techniques de rééchantillonnage.
- **Indicateurs clés :** Des variables comme la peur de la scène ('Stage_fear'), la sensation d'être vidé après
  avoir socialisé ('Drained_after_socializing') et la taille du cercle d'amis ('Friends_circle_size') se sont
  révélées être des prédicteurs très puissants.
- **Corrélation :** La matrice de corrélation a confirmé une forte corrélation (positive ou négative) entre ces
  indicateurs et la variable cible 'Personality' (scores > 0.75). Par exemple, la peur de la scène est
  fortement corrélée au fait d'être introverti.
- **Visualisation :** Les graphiques multivariés (3D et PairPlot) ont montré une séparation quasi-parfaite des deux
  classes dans l'espace des caractéristiques, suggérant qu'un modèle de classification linéaire pourrait déjà
  obtenir d'excellents résultats.

--------------------------------------------------------------------------------
**2. PRÉTRAITEMENT DES DONNÉES**
--------------------------------------------------------------------------------
Les étapes suivantes ont été réalisées pour préparer les données à la modélisation :
1.  **Nettoyage :** Remplacement des valeurs non numériques aberrantes par la médiane de leur colonne.
2.  **Encodage :** Conversion de toutes les variables textuelles (ex: 'Yes'/'No', 'Introvert'/'Extrovert') en format
    numérique (0 ou 1).
3.  **Division :** Séparation des données en un ensemble d'entraînement (80%) et un ensemble de test (20%).
4.  **Mise à l'échelle (Standardisation) :** Standardisation de toutes les caractéristiques pour qu'elles aient une
    moyenne de 0 et un écart-type de 1. Cette étape est essentielle pour les modèles sensibles à l'échelle comme
    la Régression Logistique, SVM et les Réseaux de Neurones.

--------------------------------------------------------------------------------
**3. RÉSULTATS DE LA MODÉLISATION**
--------------------------------------------------------------------------------
Sept modèles différents ont été entraînés et évalués. Voici un résumé de leurs performances (précision) sur
l'ensemble de test :

**Modèles de Machine Learning :**
- Régression Logistique :    {results_ml['Régression Logistique']:.4f}
- Arbre de Décision :        {results_ml['Arbre de Décision']:.4f}
- k-NN (k=5) :               {results_ml['k-NN (k=5)']:.4f}
- SVM (SVC) :                {results_ml['SVM (SVC)']:.4f}

**Modèles de Deep Learning :**
- ANN Simple :               {results_dl.get('ANN Simple', 0):.4f}
- ANN Profond :              {results_dl.get('ANN Profond', 0):.4f}
- ANN avec Dropout :         {results_dl.get('ANN avec Dropout', 0):.4f}

**MEILLEUR MODÈLE :**
Le modèle le plus performant est **'{best_model_name}'** avec une précision exceptionnelle de **{best_model_accuracy:.2%}**.
Ce modèle a démontré une capacité quasi parfaite à généraliser sur des données qu'il n'avait jamais vues.

--------------------------------------------------------------------------------
**4. CONCLUSION ET SAUVEGARDE**
--------------------------------------------------------------------------------
Le projet a été un succès. Nous avons identifié des caractéristiques comportementales très prédictives de la
personnalité et construit plusieurs modèles très performants.

Le pipeline complet, incluant le modèle entraîné '{best_model_name}' et le 'StandardScaler' utilisé pour le
prétraitement, a été sauvegardé dans le fichier **'pipeline_personality.joblib'**. Ce fichier est prêt à
l'emploi pour être intégré dans une application afin de réaliser des prédictions sur de nouveaux individus.

Fin du rapport.
"""

print(rapport_final)